import api from './api';
export const adminService = {
  getPendingAnnonces: () => api.get('/admin/pending-annonces'),
  verifyAnnonce: (id) => api.put('/admin/verify-annonce/' + id),
  deleteAnnonce: (id) => api.delete('/admin/annonces/' + id),
  getStats: () => api.get('/admin/stats'),
  getAnnonces: () => api.get('/admin/annonces'),
  updateAnnonce: (id, data) => api.put('/annonces/' + id, data),
  getAdminVisites: () => api.get('/visites/admin/visites'),
  getUsers: () => api.get('/admin/users'),
  deleteUser: (id) => api.delete('/admin/users/' + id),
  createUser: (data) => api.post('/admin/users', data),
  getPaiements: () => api.get('/paiements/admin'),
  getContratsBDE: () => api.get('/ambassadeurs/contrats'),
  declencherPaiement: (contratId) => api.post('/ambassadeurs/paiements', { contratId }),
  getAvisAdmin: () => api.get('/avis/admin'),
  approuverAvis: (id) => api.post('/avis/' + id + '/approuver'),
  rejeterAvis: (id) => api.post('/avis/' + id + '/rejeter'),
  syncCatalogueWhatsApp: () => api.post('/whatsapp/sync-catalogue'),
  getWhatsAppLogs: () => api.get('/whatsapp/logs'),
  getWhatsAppAnnonces: () => api.get('/whatsapp/annonces-verifiees'),
  getNotifications: () => api.get('/notifications'),
  createNotification: (data) => api.post('/notifications', data),
  marquerToutLu: () => api.post('/notifications/marquer-tout-lu'),
  getQuartiers: () => api.get('/quartiers/admin'),
  addQuartier: (data) => api.post('/quartiers', data),
  toggleQuartier: (id) => api.put('/quartiers/' + id + '/toggle'),
  deleteQuartier: (id) => api.delete('/quartiers/' + id),
  getPrix: () => api.get('/prix/admin'),
  addPrix: (data) => api.post('/prix', data),
  togglePrix: (id) => api.put('/prix/' + id + '/toggle'),
  deletePrix: (id) => api.delete('/prix/' + id),
  getPublicationStats: () => api.get('/paiements/admin/stats'),
};
export default adminService;
